Added huggingface hub login
iGavroche/BrainChulo pull request #77
Opened 2023-08-09 21:54 UTC by Walchshofer

2023-08-09 21:55 UTC, Walchshofer commented
added huggingface hub login

2023-08-10 12:52 UTC, iGavroche requested changes
Thanks for submitting a PR. Please review the comments and also join our Discord (link in Readme.md I believe) if interested in developing further.

2023-08-10 12:52 UTC, iGavroche commented on app/settings.py
> +        self.model_root_path = "/home/pwalch/textgen/models" # changed the model path
do not make this change for all users please.

2023-08-10 12:52 UTC, iGavroche commented on app/settings.py
> +            self.model_root_path = "/home/pwalch/textgen/models" # changed the model path
this changed should be managed through the `.env` file.
Also note that "/models" refers to "<your project's root folder>/models".

2023-08-10 12:52 UTC, iGavroche commented on bootstrap_models.py
> +    user = hf_api.whoami(hf_token)
make this conditional to there being a huggingface token present in `.env`. If not, continue with unauthenticated session.

2023-10-01 18:03 UTC, closed without merging